/*
	
	CBA Einstellungen
	
	Zustaendigkeit OCTI / NIKI
	
	Letzte Aktualisierung Github - 08.02.2025 - 10:17
	Letzte Aktualisierung Server - 28.01.2025 - 04:11
	Chancelog im Discord
	
	Sperrt alle Aenderungen auf Server fuer CBA Settings. Aenderungen die auf dem Server passieren, sind nur Temporaer.
	
*/

/// A3TI
force force A3TI_ACE_JAVELIN = false;
force force A3TI_ALLOW_TANK_DRIVER = false;
force force A3TI_ALLOW_VANILLA_TI = true;
force force A3TI_ENABLE_ZEUS = true;
force force A3TI_HD_VISION_FIGHTER = false;
force force A3TI_HD_VISION_LANDVEH = true;
force force A3TI_HD_VISION_SHIP = false;
force force A3TI_HD_VISION_UAV = true;
force force A3TI_REMOVE_FILMGRAIN_RHS = true;

// ACE Abschüsse
force force ace_killtracker_showCrewKills = true;
force force ace_killtracker_showMedicalWounds = 2;
force force ace_killtracker_trackAI = true;

// ACE Allgemein
force force ace_common_allowFadeMusic = true;
force force ace_common_checkExtensions = false;
force force ace_common_checkPBOsAction = 0;
force force ace_common_checkPBOsCheckAll = false;
force force ace_common_checkPBOsWhitelist = "[]";
force force ace_common_deployedSwayFactor = 0.4;
force force ace_common_displayTextColor = [0,0,0,0.1];
force force ace_common_displayTextFontColor = [1,1,1,1];
force force ace_common_enableSway = true;
ace_common_epilepsyFriendlyMode = false;
force force ace_common_magneticDeclination = false;
force force ace_common_progressBarInfo = 2;
force force ace_common_restedSwayFactor = 0.4;
force force ace_common_settingFeedbackIcons = 1;
force force ace_common_settingProgressBarLocation = 0;
force force ace_common_swayFactor = 0.4;

// ACE Artillerie
force force ace_artillerytables_advancedCorrections = false;
force force ace_artillerytables_disableArtilleryComputer = false;
force force ace_mk6mortar_airResistanceEnabled = false;
force force ace_mk6mortar_allowCompass = true;
force force ace_mk6mortar_allowComputerRangefinder = true;
force force ace_mk6mortar_useAmmoHandling = true;

// ACE Außenlaststationen
force force ace_pylons_enabledForZeus = true;
force force ace_pylons_enabledFromAmmoTrucks = true;
force force ace_pylons_rearmNewPylons = true;
force force ace_pylons_requireEngineer = false;
force force ace_pylons_requireToolkit = false;
force force ace_pylons_searchDistance = 25;
force force ace_pylons_timePerPylon = 10;

// ACE Benutzeroberfläche
force force ace_ui_allowSelectiveUI = false;
force force ace_ui_ammoCount = false;
force force ace_ui_ammoType = true;
force force ace_ui_commandMenu = true;
force force ace_ui_enableSpeedIndicator = true;
force force ace_ui_firingMode = true;
force force ace_ui_groupBar = true;
force force ace_ui_gunnerAmmoCount = true;
force force ace_ui_gunnerAmmoType = true;
force force ace_ui_gunnerFiringMode = true;
force force ace_ui_gunnerLaunchableCount = true;
force force ace_ui_gunnerLaunchableName = true;
force force ace_ui_gunnerMagCount = true;
force force ace_ui_gunnerWeaponLowerInfoBackground = true;
force force ace_ui_gunnerWeaponName = true;
force force ace_ui_gunnerWeaponNameBackground = true;
force force ace_ui_gunnerZeroing = true;
ace_ui_hideDefaultActionIcon = false;
force force ace_ui_magCount = true;
force force ace_ui_soldierVehicleWeaponInfo = true;
force force ace_ui_staminaBar = true;
force force ace_ui_stance = true;
force force ace_ui_throwableCount = true;
force force ace_ui_throwableName = true;
force force ace_ui_vehicleAltitude = true;
force force ace_ui_vehicleCompass = true;
force force ace_ui_vehicleDamage = true;
force force ace_ui_vehicleFuelBar = true;
force force ace_ui_vehicleInfoBackground = true;
force force ace_ui_vehicleName = true;
force force ace_ui_vehicleNameBackground = true;
force force ace_ui_vehicleRadar = true;
force force ace_ui_vehicleSpeed = true;
force force ace_ui_weaponLowerInfoBackground = true;
force force ace_ui_weaponName = true;
force force ace_ui_weaponNameBackground = true;
force force ace_ui_zeroing = true;

// ACE Crew Served Weapons
force force ace_csw_ammoHandling = 1;
force force ace_csw_defaultAssemblyMode = false;
force force ace_csw_dragAfterDeploy = false;
force force ace_csw_handleExtraMagazines = true;
force force ace_csw_handleExtraMagazinesType = 1;
force force ace_csw_progressBarTimeCoefficent = 0.8;

// ACE Durchzündung
force force ace_cookoff_ammoCookoffDuration = 0.853711;
force force ace_cookoff_cookoffDuration = 1;
force force ace_cookoff_destroyVehicleAfterCookoff = true;
force force ace_cookoff_enableAmmobox = true;
force force ace_cookoff_enableAmmoCookoff = false;
force force ace_cookoff_enableFire = true;
force force ace_cookoff_probabilityCoef = 0.8;
force force ace_cookoff_removeAmmoDuringCookoff = true;

// ACE Einheitenwechsel
force force ace_switchunits_enableSafeZone = false;
force force ace_switchunits_enableSwitchUnits = false;
force force ace_switchunits_safeZoneRadius = 100;
force force ace_switchunits_switchToCivilian = false;
force force ace_switchunits_switchToEast = false;
force force ace_switchunits_switchToIndependent = false;
force force ace_switchunits_switchToWest = false;

// ACE Erweiterte Ausdauer
force force ace_advanced_fatigue_enabled = true;
force force ace_advanced_fatigue_enableStaminaBar = true;
force force ace_advanced_fatigue_fadeStaminaBar = true;
force force ace_advanced_fatigue_loadFactor = 0.8;
force force ace_advanced_fatigue_performanceFactor = 1;
force force ace_advanced_fatigue_recoveryFactor = 3;
force force ace_advanced_fatigue_terrainGradientFactor = 0.8;

// ACE Erweiterte Ballistik
force force ace_advanced_ballistics_ammoTemperatureEnabled = true;
force force ace_advanced_ballistics_barrelLengthInfluenceEnabled = true;
force force ace_advanced_ballistics_bulletTraceEnabled = true;
force force ace_advanced_ballistics_enabled = true;
force force ace_advanced_ballistics_muzzleVelocityVariationEnabled = true;
force force ace_advanced_ballistics_simulationInterval = 0.05;

// ACE Erweiterter Fahrzeugsschaden
force force ace_vehicle_damage_enableCarDamage = true;
force force ace_vehicle_damage_enabled = true;

// ACE Erweitertes Wurfsystem
force force ace_advanced_throwing_enabled = true;
force force ace_advanced_throwing_enablePickUp = true;
force force ace_advanced_throwing_enablePickUpAttached = true;
force force ace_advanced_throwing_enableTempWindInfo = true;
force force ace_advanced_throwing_showMouseControls = true;
force force ace_advanced_throwing_showThrowArc = true;

// ACE Fahrzeuge
force force ace_novehicleclanlogo_enabled = false;
ace_vehicles_hideEjectAction = false;
force force ace_vehicles_keepEngineRunning = true;
force force ace_vehicles_speedLimiterStep = 5;
force force ace_viewports_enabled = true;

// ACE Fahrzeugsperre
force force ace_vehiclelock_defaultLockpickStrength = 10;
force force ace_vehiclelock_lockVehicleInventory = false;
force force ace_vehiclelock_vehicleStartingLockState = -1;

// ACE Feld Rationen
force force ace_field_rations_zeusUpdates = false;
force force acex_field_rations_affectAdvancedFatigue = true;
force force acex_field_rations_enabled = false;
force force acex_field_rations_hudShowLevel = 0;
force force acex_field_rations_hudTransparency = -1;
force force acex_field_rations_hudType = 0;
force force acex_field_rations_hungerSatiated = 2;
force force acex_field_rations_nearDepletedConsequence = 1;
force force acex_field_rations_terrainObjectActions = true;
force force acex_field_rations_thirstQuenched = 2;
force force acex_field_rations_timeWithoutFood = 3;
force force acex_field_rations_timeWithoutWater = 2;
force force acex_field_rations_waterSourceActions = 2;

// ACE Feuer
force force ace_fire_dropWeapon = 1;
force force ace_fire_enabled = true;
force force ace_fire_enableFlare = true;
force force ace_fire_enableScreams = true;

// ACE Fingerzeig
force force ace_finger_enabled = true;
force force ace_finger_indicatorColor = [1,0.503034,0,1];
force force ace_finger_indicatorForSelf = true;
force force ace_finger_maxRange = 5.01867;
force force ace_finger_proximityScaling = false;
force force ace_finger_sizeCoef = 1;

// ACE G-Kräfte
force force ace_gforces_coef = 0.5;
force force ace_gforces_enabledFor = 1;

// ACE Gefangene
force force ace_captives_allowHandcuffOwnSide = true;
force force ace_captives_allowSurrender = true;
force force ace_captives_requireSurrender = 2;
force force ace_captives_requireSurrenderAi = false;

// ACE Gehör
force force ace_hearing_autoAddEarplugsToUnits = 2;
ace_hearing_disableEarRinging = true;
force force ace_hearing_earplugsVolume = 1;
force force ace_hearing_enableCombatDeafness = false;
force force ace_hearing_enabledForZeusUnits = false;
force force ace_hearing_enableNoiseDucking = true;
force force ace_hearing_explosionDeafnessCoefficient = 1;
force force ace_hearing_unconsciousnessVolume = 0.4;

// ACE Gräben
force force ace_trenches_bigEnvelopeDigDuration = 25;
force force ace_trenches_bigEnvelopeRemoveDuration = 15;
force force ace_trenches_smallEnvelopeDigDuration = 20;
force force ace_trenches_smallEnvelopeRemoveDuration = 12;

// ACE Granaten
force force ace_grenades_convertExplosives = true;

// ACE Headless
force force acex_headless_delay = 5;
force force acex_headless_enabled = true;
force force acex_headless_endMission = 0;
force force acex_headless_log = true;
force force acex_headless_transferLoadout = 1;

// ACE Heißlaufen
force force ace_overheating_cookoffCoef = 1;
force force ace_overheating_coolingCoef = 1;
force force ace_overheating_displayTextOnJam = true;
force force ace_overheating_enabled = true;
force force ace_overheating_heatCoef = 1.2;
force force ace_overheating_jamChanceCoef = 1;
force force ace_overheating_overheatingDispersion = true;
force force ace_overheating_overheatingRateOfFire = true;
force force ace_overheating_particleEffectsAndDispersionDistance = 1000;
force force ace_overheating_showParticleEffects = true;
force force ace_overheating_showParticleEffectsForEveryone = false;
force force ace_overheating_suppressorCoef = 1;
force force ace_overheating_unJamFailChance = 0.25;
force force ace_overheating_unJamOnreload = false;
force force ace_overheating_unJamOnSwapBarrel = false;

// ACE Hinsetzen
force force acex_sitting_enable = true;

// ACE Interaktion
force force ace_interaction_disableNegativeRating = true;
force force ace_interaction_enableAnimActions = true;
force force ace_interaction_enableGroupRenaming = true;
force force ace_interaction_enableMagazinePassing = true;
force force ace_interaction_enableTeamManagement = true;
force force ace_interaction_enableThrowablePassing = true;
force force ace_interaction_enableWeaponAttachments = true;
force force ace_interaction_interactWithEnemyCrew = 0;
force force ace_interaction_interactWithTerrainObjects = false;
force force ace_interaction_remoteTeamManagement = true;

// ACE Interaktionsmenü
force force ace_gestures_showOnInteractionMenu = 2;
force force ace_interact_menu_actionOnKeyRelease = true;
force force ace_interact_menu_addBuildingActions = false;
force force ace_interact_menu_alwaysUseCursorInteraction = false;
force force ace_interact_menu_alwaysUseCursorSelfInteraction = true;
force force ace_interact_menu_colorShadowMax = [0,0,0,1];
force force ace_interact_menu_colorShadowMin = [0,0,0,0.25];
force force ace_interact_menu_colorTextMax = [1,1,1,1];
force force ace_interact_menu_colorTextMin = [1,1,1,0.25];
force force ace_interact_menu_consolidateSingleChild = false;
force force ace_interact_menu_cursorKeepCentered = false;
force force ace_interact_menu_cursorKeepCenteredSelfInteraction = false;
force force ace_interact_menu_menuAnimationSpeed = 0;
force force ace_interact_menu_menuBackground = 0;
force force ace_interact_menu_menuBackgroundSelf = 0;
force force ace_interact_menu_selectorColor = [1,0,0];
force force ace_interact_menu_shadowSetting = 2;
force force ace_interact_menu_textSize = 2;
ace_interact_menu_useListMenu = true;
ace_interact_menu_useListMenuSelf = true;

// ACE Interaktionsmenü (selbst) - Mehr
ace_interact_menu_more__ACE_CheckAirTemperature = false;
ace_interact_menu_more__ace_csw_deploy = false;
ace_interact_menu_more__ACE_Equipment = false;
ace_interact_menu_more__ACE_Explosives = false;
ace_interact_menu_more__ace_field_rations = false;
ace_interact_menu_more__ace_fortify = false;
ace_interact_menu_more__ace_gestures = false;
ace_interact_menu_more__ace_intelitems = false;
ace_interact_menu_more__ACE_MapFlashlight = false;
ace_interact_menu_more__ACE_MapGpsHide = false;
ace_interact_menu_more__ACE_MapGpsShow = false;
ace_interact_menu_more__ACE_MapTools = false;
ace_interact_menu_more__ACE_Medical = false;
ace_interact_menu_more__ace_medical_ai_heal = false;
ace_interact_menu_more__ACE_Medical_Menu = false;
ace_interact_menu_more__ACE_MoveRallypoint = false;
ace_interact_menu_more__ACE_PlottingBoard = false;
ace_interact_menu_more__ACE_PlottingBoardHide = false;
ace_interact_menu_more__ACE_RepackMagazines = false;
ace_interact_menu_more__ace_sandbag_place = false;
ace_interact_menu_more__ACE_StartSurrenderingSelf = false;
ace_interact_menu_more__ACE_StopEscortingSelf = false;
ace_interact_menu_more__ACE_StopSurrenderingSelf = false;
ace_interact_menu_more__ACE_Tags = false;
ace_interact_menu_more__ACE_TeamManagement = false;
ace_interact_menu_more__ace_zeus_create = false;
ace_interact_menu_more__ace_zeus_delete = false;
ace_interact_menu_more__acex_sitting_Stand = false;
ace_interact_menu_more__ACRE_Interact = false;
ace_interact_menu_more__acre_sys_zeus_playerEars = false;
ace_interact_menu_more__acre_sys_zeus_remoteEars = false;
ace_interact_menu_more__cTab_Interact = false;
ace_interact_menu_more__KAT_Equipment = false;
ace_interact_menu_more__kka3_anim = false;
ace_interact_menu_more__Medical = false;
ace_interact_menu_more__mts_cords_cordAction = false;
ace_interact_menu_more__SSS_main = false;

// ACE Interaktionsmenü (selbst) - Zu Ursprung bewegen
ace_interact_menu_moveToRoot__ACE_Equipment__ace_atragmx_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_attach_Attach = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_attach_Detach = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_CheckDogtags = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_Chemlights = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_dagr_menu = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_dagr_menu__ace_dagr_toggle = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_flags = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_flags__ace_flags_furlFlag = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_goggles_wipeGlasses = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_status = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponOff = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponSwap = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponTo = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_huntir_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_interaction_weaponAttachments = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open__ace_kestrel4500_hide = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open__ace_kestrel4500_show = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_marker_flags = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure__ace_microdagr_close = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure__ace_microdagr_show = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_activate = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_connectHeadphones = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_deactivate = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_disconnectHeadphones = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_mk6mortar_rangetable = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CheckTemperature = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CheckTemperatureSpareBarrels = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CoolWeaponWithItem = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_SwapBarrel = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_UnJam = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_PutInEarplugs = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_PutOnEHP = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open__ace_rangecard_makeCopy = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open__ace_rangecard_openCopy = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_reload_checkAmmo = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_RemoveEarplugs = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_RemoveEHP = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_scopes_adjustZero = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_scopes_resetZero = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_spottingscope_place = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_TacticalLadders = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__ace_trenches_digEnvelopeBig = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__ace_trenches_digEnvelopeSmall = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeGiant = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeLongNameEmplacment = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeShort = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeVehicle = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_tripod_place = false;
ace_interact_menu_moveToRoot__ACE_Equipment__acre_sys_gsa_placeSpike = false;
ace_interact_menu_moveToRoot__ACE_Equipment__acre_sys_gsa_placeSpikeMast = false;
ace_interact_menu_moveToRoot__ACE_Equipment__GRAD_slingHelmet_sling = false;
ace_interact_menu_moveToRoot__ACE_Equipment__GRAD_slingHelmet_swap = false;
ace_interact_menu_moveToRoot__ACE_Equipment__GRAD_slingHelmet_unsling = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeCampfireburningF = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeLandBagFenceLong = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeLandBagFenceRound = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeLandCampingChairV1F = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeLandCampingLightoffF = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeLandCampingTableF = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeLandPalletvertical = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeLandPortableLightsingle = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeRoadBarrier = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeRoadBarriersmall = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeRoadCone = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeRoadConeLight = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeTapeSignF = false;
ace_interact_menu_moveToRoot__ACE_Equipment__kka3_placeTargetF = false;
ace_interact_menu_moveToRoot__ACE_Equipment__mts_cutter_bushcutter = false;
ace_interact_menu_moveToRoot__ACE_Equipment__mts_cutter_grasscutter = false;
ace_interact_menu_moveToRoot__ACE_Equipment__mts_items = false;
ace_interact_menu_moveToRoot__ACE_Equipment__mts_map_placeMapAction = false;
ace_interact_menu_moveToRoot__ACE_Explosives__ACE_Cellphone = false;
ace_interact_menu_moveToRoot__ACE_Explosives__ACE_Place = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Advance = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_CeaseFire = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Cover = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Engage = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Follow = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Forward = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Freeze = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Go = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Hold = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Point = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Regroup = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Stop = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Up = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Warning = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignCompass = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignNorth = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignToPlottingBoard = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignToPlottingBoardAcrylic = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignToPlottingBoardRuler = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsHide = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsShowNormal = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsShowSmall = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_ArmLeft = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_ArmRight = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Head = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_LegLeft = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_LegRight = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Torso = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Torso__TriageCard = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignAcrylic = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignAcrylic__ACE_PlottingBoardAlignAcrylicMaptool = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignAcrylic__ACE_PlottingBoardAlignAcrylicUp = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignBoard = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignBoard__ACE_PlottingBoardAlignBoardMaptool = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignBoard__ACE_PlottingBoardAlignBoardUp = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignRuler = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignRuler__ACE_PlottingBoardAlignRulerMaptool = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignRuler__ACE_PlottingBoardAlignRulerUp = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardRulerHide = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardRulerShow = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardWipe = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_BecomeLeader = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamBlue = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamGreen = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamMain = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamRed = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamYellow = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_LeaveGroup = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_remoteTeamManagement = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_RenameGroup = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__diwako_dui_buddy_buddy_action_team_remove = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingLeftArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingLeftLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingRightArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingRightLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Attach_PersonalOxygen = false;
ace_interact_menu_moveToRoot__KAT_Equipment__BubbleWrapPopping = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Check_PersonalOxygen = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Detach_PersonalOxygen = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions__KAT_AED_X_addSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions__KAT_AED_X_removeSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions__KAT_AED_X_ViewMonitor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__AFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__AFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot1_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot2_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot3_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot4_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot5_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot6_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChangeGasMaskFilter = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_CheckGasMaskDur = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_CheckHandWarmersSelf = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector__KAT_ChemicalDetector_Enable = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector__KAT_ChemicalDetector_SoundOff = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector__KAT_ChemicalDetector_SoundOn = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_DeployStretcher = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__IFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__IFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot1_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot2_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot3_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot4_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__MFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot7 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot8 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__MFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot1_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot2_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot3_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot4_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot5_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot6_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot7 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot7_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot8 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot8_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_placeAED = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_placeAEDX = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_PutOnGasMask = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_TakeOffGasMask = false;
ace_interact_menu_moveToRoot__KAT_Equipment__openCrossPanel = false;
ace_interact_menu_moveToRoot__KAT_Equipment__PulseOximeter_addSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__PulseOximeter_removeSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Refill_OxygenTank_150_Facility = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Refill_OxygenTank_300_Facility = false;
ace_interact_menu_moveToRoot__KAT_Equipment__SetPreferred_OxygenTank_150 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__SetPreferred_OxygenTank_300 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_actions = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_actions__kka3_direonepeace = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_actions__kka3_direonerock = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_actions__kka3_Facepalm = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_actions__kka3_kata = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_actions__kka3_pissing = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_actions__kka3_Pushup = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_actions__kka3_Threaten = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_actions__kka3_Thumbsup = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_cancel = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier__kka3_crouch = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier__kka3_crouch_thumbup = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier__kka3_EmergencyStop = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier__kka3_EnginesOff = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier__kka3_EnginesOn = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier__kka3_Launch = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier__kka3_Left = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier__kka3_Right = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier__kka3_Slow = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier__kka3_Stop = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_carrier__kka3_Straight = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_dance = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_dance__kka3_Crazy_Dance = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_dance__kka3_crazydrunkdance = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_dance__kka3_dubstepdance = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_dance__kka3_dubstepPop = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_dance__kka3_DuoIvan = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_dance__kka3_hiphopdance = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_dance__kka3_nightclubdance = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_dance__kka3_robotdance = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_dance__kka3_russiandance = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone2 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone2__kka3_direone1b = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone2__kka3_direone2b = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone2__kka3_direone3b = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone__kka3_direone_1 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone__kka3_direone_2 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone__kka3_direone_3 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone__kka3_direone_4 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone__kka3_direone_5 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone__kka3_direone_6 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_direone__kka3_direone_7 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_emotion = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_emotion__kka3_mimic = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_emotion__kka3_mimic__kka3_Angry = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_emotion__kka3_mimic__kka3_Default = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_emotion__kka3_mimic__kka3_Sad = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_emotion__kka3_mimic__kka3_Smile = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_emotion__kka3_scared = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_poses = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_poses__kka3_pose1 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_poses__kka3_pose10 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_poses__kka3_pose2 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_poses__kka3_pose3 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_poses__kka3_pose4 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_poses__kka3_pose5 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_poses__kka3_pose6 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_poses__kka3_pose7 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_poses__kka3_pose8 = false;
ace_interact_menu_moveToRoot__kka3_anim__kka3_poses__kka3_pose9 = false;
ace_interact_menu_moveToRoot__Medical__ACE_Head = false;
ace_interact_menu_moveToRoot__Medical__ACE_Head__CheckBloodPressure = false;
ace_interact_menu_moveToRoot__mts_cords_cordAction__mts_cords_infCordAction = false;
ace_interact_menu_moveToRoot__mts_cords_cordAction__mts_cords_infCordAction__mts_cords_faCordAction = false;
ace_interact_menu_moveToRoot__mts_cords_cordAction__mts_cords_infCordAction__mts_cords_oaCordAction = false;
ace_interact_menu_moveToRoot__mts_cords_cordAction__mts_cords_pzCordAction = false;
ace_interact_menu_moveToRoot__mts_cords_cordAction__mts_cords_pzCordAction__mts_cords_pzFACordAction = false;
ace_interact_menu_moveToRoot__mts_cords_cordAction__mts_cords_pzCordAction__mts_cords_pzOACordAction = false;
ace_interact_menu_moveToRoot__SSS_main__SSS_artillery = false;
ace_interact_menu_moveToRoot__SSS_main__SSS_CAS = false;
ace_interact_menu_moveToRoot__SSS_main__SSS_logistics = false;
ace_interact_menu_moveToRoot__SSS_main__SSS_transport = false;

// ACE Karte
force force ace_map_BFT_Enabled = false;
force force ace_map_BFT_HideAiGroups = true;
force force ace_map_BFT_Interval = 1;
force force ace_map_BFT_ShowPlayerNames = false;
force force ace_map_DefaultChannel = 1;
force force ace_map_mapGlow = true;
force force ace_map_mapIllumination = true;
force force ace_map_mapLimitZoom = false;
force force ace_map_mapShake = true;
force force ace_map_mapShowCursorCoordinates = false;
force force ace_markers_moveRestriction = 0;
force force ace_markers_timestampEnabled = true;
force force ace_markers_timestampFormat = "HH:MM";
force force ace_markers_timestampHourFormat = 24;
force force ace_markers_timestampTimezone = 0;
force force ace_markers_TimestampUTCMinutesOffset = 0;
force force ace_markers_timestampUTCOffset = 0;

// ACE Kartenwerkzeug
force force ace_maptools_drawStraightLines = true;
force force ace_maptools_plottingBoardAllowChannelDrawing = 1;
force force ace_maptools_rotateModifierKey = 1;

// ACE Kartenzeichen
force force ace_map_gestures_allowCurator = true;
force force ace_map_gestures_allowSpectator = true;
force force ace_map_gestures_briefingMode = 0;
force force ace_map_gestures_defaultColor = [1,0.88,0,0.7];
force force ace_map_gestures_defaultLeadColor = [1,0,0,0.95];
force force ace_map_gestures_enabled = true;
force force ace_map_gestures_interval = 0.03;
force force ace_map_gestures_maxRange = 7;
force force ace_map_gestures_maxRangeCamera = 14;
force force ace_map_gestures_nameTextColor = [0.2,0.2,0.2,0.3];
force force ace_map_gestures_onlyShowFriendlys = false;

// ACE KI
force force ace_ai_assignNVG = false;

// ACE Lautstärke
force force acex_volume_enabled = true;
force force acex_volume_fadeDelay = 0;
force force acex_volume_lowerInVehicles = true;
force force acex_volume_reduction = 1;
force force acex_volume_remindIfLowered = false;
force force acex_volume_showNotification = true;

// ACE Logistik
force force ace_cargo_carryAfterUnload = true;
force force ace_cargo_checkSizeInteraction = true;
force force ace_cargo_enable = true;
force force ace_cargo_enableDeploy = true;
force force ace_cargo_enableRename = true;
force force ace_cargo_loadTimeCoefficient = 5;
force force ace_cargo_openAfterUnload = 0;
force force ace_cargo_paradropTimeCoefficent = 2.45351;
force force ace_rearm_distance = 25;
force force ace_rearm_enabled = true;
force force ace_rearm_level = 0;
force force ace_rearm_supply = 0;
force force ace_refuel_cargoRate = 10;
force force ace_refuel_enabled = true;
force force ace_refuel_hoseLength = 25;
force force ace_refuel_progressDuration = 1;
force force ace_refuel_rate = 1;
force force ace_towing_addRopeToVehicleInventory = true;

// ACE Magazine umpacken
force force ace_magazinerepack_repackAnimation = true;
force force ace_magazinerepack_repackLoadedMagazines = true;
force force ace_magazinerepack_timePerAmmo = 1.5;
force force ace_magazinerepack_timePerBeltLink = 8;
force force ace_magazinerepack_timePerMagazine = 2;

// ACE Patronenhülsen
force force ace_casings_enabled = true;
force force ace_casings_maxCasings = 250;

// ACE Reparieren
force force ace_repair_addSpareParts = true;
force force ace_repair_autoShutOffEngineWhenStartingRepair = true;
force force ace_repair_consumeItem_toolKit = 0;
force force ace_repair_displayTextOnRepair = true;
force force ace_repair_enabled = true;
force force ace_repair_engineerSetting_fullRepair = 2;
force force ace_repair_engineerSetting_repair = 2;
force force ace_repair_engineerSetting_wheel = 0;
force force ace_repair_fullRepairLocation = 0;
force force ace_repair_fullRepairRequiredItems = ["ace_repair_anyToolKit"];
force force ace_repair_locationsBoostTraining = false;
force force ace_repair_miscRepairRequiredItems = ["ace_repair_anyToolKit"];
force force ace_repair_miscRepairTime = 5;
force force ace_repair_patchWheelEnabled = 0;
force force ace_repair_patchWheelLocation = ["ground","vehicle"];
force force ace_repair_patchWheelMaximumRepair = 0.3;
force force ace_repair_patchWheelRequiredItems = ["ace_repair_anyToolKit"];
force force ace_repair_patchWheelTime = 5;
force force ace_repair_repairDamageThreshold = 1;
force force ace_repair_repairDamageThreshold_engineer = 1;
force force ace_repair_timeCoefficientFullRepair = 1.5;
force force ace_repair_wheelChangeTime = 10;
force force ace_repair_wheelRepairRequiredItems = [];

// ACE Schnellzugang
force force ace_quickmount_distance = 5;
force force ace_quickmount_enabled = true;
force force ace_quickmount_enableMenu = 3;
force force ace_quickmount_priority = 0;
force force ace_quickmount_speed = 20;

// ACE Schutzbrille
force force ace_goggles_drawOverlay = true;
force force ace_goggles_effects = 3;
force force ace_goggles_showClearGlasses = true;
force force ace_goggles_showInThirdPerson = false;

// ACE Sichteinschränkungen
force force acex_viewrestriction_mode = 1;
force force acex_viewrestriction_modeSelectiveAir = 1;
force force acex_viewrestriction_modeSelectiveFoot = 1;
force force acex_viewrestriction_modeSelectiveLand = 1;
force force acex_viewrestriction_modeSelectiveSea = 1;
force force acex_viewrestriction_preserveView = false;

// ACE Sichtweitenbegrenzung
force force ace_viewdistance_enabled = true;
force force ace_viewdistance_limitViewDistance = 4000;
force force ace_viewdistance_objectViewDistanceCoeff = 0;
force force ace_viewdistance_viewDistanceAirVehicle = 3000;
force force ace_viewdistance_viewDistanceLandVehicle = 2500;
force force ace_viewdistance_viewDistanceOnFoot = 1500;

// ACE Splittersimulation
force force ace_frag_enabled = true;
force force ace_frag_reflectionsEnabled = true;
force force ace_frag_spallEnabled = true;
force force ace_frag_spallIntensity = 1;

// ACE Sprengstoffe
force force ace_explosives_customTimerDefault = 30;
force force ace_explosives_customTimerMax = 3600;
force force ace_explosives_customTimerMin = 5;
force force ace_explosives_explodeOnDefuse = false;
force force ace_explosives_punishNonSpecialists = true;
force force ace_explosives_requireSpecialist = true;

// ACE Unkategorisiert
force force ace_fastroping_autoAddFRIES = true;
force force ace_fastroping_requireRopeItems = false;
force force ace_flags_enableCarrying = true;
force force ace_flags_enablePlacing = true;
force force ace_gunbag_swapGunbagEnabled = true;
force force ace_hitreactions_minDamageToTrigger = 0.122781;
force force ace_hitreactions_weaponDropChanceArmHitAI = 0;
force force ace_hitreactions_weaponDropChanceArmHitPlayer = 0;
force force ace_inventory_inventoryDisplaySize = 1;
force force ace_laser_dispersionCount = 2;
force force ace_laser_showLaserOnMap = 1;
force force ace_marker_flags_placeAnywhere = true;
force force ace_microdagr_mapDataAvailable = 2;
force force ace_microdagr_waypointPrecision = 3;
force force ace_noradio_enabled = true;
force force ace_optionsmenu_showNewsOnMainMenu = false;
force force ace_overpressure_backblastDistanceCoefficient = 1;
force force ace_overpressure_overpressureDistanceCoefficient = 1;
force force ace_parachute_failureChance = 0;
force force ace_parachute_hideAltimeter = true;
force force ace_tagging_quickTag = 1;

// ACE Verstärken
force force ace_fortify_markObjectsOnMap = 1;
force force ace_fortify_timeCostCoefficient = 1;
force force ace_fortify_timeMin = 1.5;
force force acex_fortify_settingHint = 1;

// ACE Waffen
force force ace_common_persistentLaserEnabled = true;
force force ace_reload_displayText = true;
force force ace_reload_showCheckAmmoSelf = true;
ace_reloadlaunchers_displayStatusText = true;
force force ace_weaponselect_displayText = true;

// ACE Wetter
force force ace_weather_enabled = false;
force force ace_weather_showCheckAirTemperature = true;
force force ace_weather_updateInterval = 60;
force force ace_weather_windSimulation = false;

// ACE Wiedereinstieg
force force ace_respawn_removeDeadBodiesDisconnected = false;
force force ace_respawn_savePreDeathGear = false;

// ACE Windablenkung
force force ace_winddeflection_enabled = true;
force force ace_winddeflection_simulationInterval = 0.05;
force force ace_winddeflection_vehicleEnabled = true;

// ACE Zeige Spielernamen
force force ace_nametags_ambientBrightnessAffectViewDist = 1;
force force ace_nametags_defaultNametagColor = [0.77,0.51,0.08,1];
force force ace_nametags_nametagColorBlue = [0.67,0.67,1,1];
force force ace_nametags_nametagColorGreen = [0.67,1,0.67,1];
force force ace_nametags_nametagColorMain = [1,1,1,1];
force force ace_nametags_nametagColorRed = [1,0.67,0.67,1];
force force ace_nametags_nametagColorYellow = [1,1,0.67,1];
force force ace_nametags_playerNamesMaxAlpha = 1;
force force ace_nametags_playerNamesViewDistance = 2;
force force ace_nametags_showCursorTagForVehicles = true;
force force ace_nametags_showNamesForAI = true;
force force ace_nametags_showPlayerNames = 1;
force force ace_nametags_showPlayerRanks = false;
force force ace_nametags_showSoundWaves = 2;
force force ace_nametags_showVehicleCrewInfo = true;
force force ace_nametags_tagSize = 1;

// ACE Zeus
force force ace_zeus_autoAddObjects = true;
force force ace_zeus_canCreateZeus = 0;
force force ace_zeus_radioOrdnance = false;
force force ace_zeus_remoteWind = false;
force force ace_zeus_revealMines = 0;
force force ace_zeus_zeusAscension = false;
force force ace_zeus_zeusBird = false;

// ACE Ziehen
force force ace_dragging_allowRunWithLightweight = true;
force force ace_dragging_dragAndFire = true;
force force ace_dragging_skipContainerWeight = true;
force force ace_dragging_weightCoefficient = 1;

// ACE Zielfernrohre
force force ace_scopes_correctZeroing = true;
force force ace_scopes_deduceBarometricPressureFromTerrainAltitude = true;
force force ace_scopes_defaultZeroRange = 100;
force force ace_scopes_enabled = true;
force force ace_scopes_forceUseOfAdjustmentTurrets = true;
ace_scopes_inScopeAdjustment = false;
force force ace_scopes_overwriteZeroRange = true;
force force ace_scopes_simplifiedZeroing = true;
ace_scopes_useLegacyUI = true;
force force ace_scopes_zeroReferenceBarometricPressure = 1013.25;
force force ace_scopes_zeroReferenceHumidity = 0;
force force ace_scopes_zeroReferenceTemperature = 15;

// ACE Zuschauer
force force ace_spectator_enableAI = true;
force force ace_spectator_maxFollowDistance = 5;
force force ace_spectator_restrictModes = 0;
force force ace_spectator_restrictVisions = 0;

// ACE-Arsenal
force force ace_arsenal_allowDefaultLoadouts = true;
force force ace_arsenal_allowSharedLoadouts = true;
force force ace_arsenal_camInverted = false;
ace_arsenal_defaultToFavorites = false;
force force ace_arsenal_enableIdentityTabs = true;
force force ace_arsenal_enableModIcons = 1;
ace_arsenal_EnableRPTLog = true;
ace_arsenal_favoritesColor = [0.9,0.875,0.6];
force force ace_arsenal_fontHeight = 5.5;
force force ace_arsenal_loadoutsSaveFace = true;
force force ace_arsenal_loadoutsSaveInsignia = true;
force force ace_arsenal_loadoutsSaveVoice = true;
ace_arsenal_showUnavailableItems = 0;

// ACE-Nachtsicht
force force ace_nightvision_aimDownSightsBlur = 0.2;
force force ace_nightvision_disableNVGsWithSights = false;
force force ace_nightvision_effectScaling = 0.4;
force force ace_nightvision_fogScaling = 0;
force force ace_nightvision_noiseScaling = 0.1;
force force ace_nightvision_shutterEffects = true;

// ACRE2
force force acre_sys_core_automaticAntennaDirection = true;
force force acre_sys_core_defaultRadioVolume = 0.8;
force force acre_sys_core_fullDuplex = true;
force force acre_sys_core_godVolume = 1;
force force acre_sys_core_ignoreAntennaDirection = true;
force force acre_sys_core_interference = true;
force force acre_sys_core_postmixGlobalVolume = 1;
force force acre_sys_core_premixGlobalVolume = 1;
force force acre_sys_core_revealToAI = 1;
force force acre_sys_core_spectatorVolume = 1;
force force acre_sys_core_terrainLoss = 0;
force force acre_sys_core_ts3ChannelName = "ACRE2";
force force acre_sys_core_ts3ChannelPassword = "arma3";
force force acre_sys_core_ts3ChannelSwitch = true;
force force acre_sys_core_unmuteClients = true;
force force acre_sys_radio_defaultRadio = "ACRE_SEM52SL";
force force acre_sys_signal_signalModel = 2;

// ACRE2 Gesten
force force acre_sys_gestures_enabled = true;
force acre_sys_gestures_showConnectorRopes = true;
force force acre_sys_gestures_stopADS = true;

// ACRE2 Nutzeroberfläche
force force acre_sys_godmode_rxNotification = true;
force force acre_sys_godmode_rxNotificationColor = [0.8,0.8,0.8,1];
force force acre_sys_godmode_txNotification = true;
force force acre_sys_godmode_txNotificationCurrentChatColor = [0.8,0.8,0.8,1];
force force acre_sys_godmode_txNotificationGroup1Color = [0.8,0.8,0.8,1];
force force acre_sys_godmode_txNotificationGroup2Color = [0.8,0.8,0.8,1];
force force acre_sys_godmode_txNotificationGroup3Color = [0.8,0.8,0.8,1];
force force acre_sys_gui_volumeColorScale = [[1,1,0,0.5],[1,0.83,0,0.5],[1,0.65,0,0.5],[1,0.44,0,0.5],[1,0,0,0.5]];
force force acre_sys_list_CycleRadiosColor = [0.66,0.05,1,1];
force force acre_sys_list_DefaultPTTColor = [1,0.8,0,1];
force force acre_sys_list_HintBackgroundColor = [0,0,0,0.8];
force force acre_sys_list_HintTextFont = "RobotoCondensed";
force force acre_sys_list_LanguageColor = [1,0.29,0.16,1];
acre_sys_list_LanguageHintPersist = true;
force force acre_sys_list_PTT1Color = [1,0.8,0,1];
force force acre_sys_list_PTT2Color = [1,0.8,0,1];
force force acre_sys_list_PTT3Color = [1,0.8,0,1];
force force acre_sys_list_SwitchChannelColor = [0.66,0.05,1,1];
force force acre_sys_list_ToggleHeadsetColor = [0.66,0.05,1,1];

// ACRE2 Zeus
force force acre_sys_zeus_zeusCanSpectate = true;
force force acre_sys_zeus_zeusCommunicateViaCamera = true;
force force acre_sys_zeus_zeusDefaultVoiceSource = false;

// Advanced Vault System
force AVS_EnableVoiceSounds = true;
force force AVS_Jump_MAINWEAP_X = "4";
force force AVS_Jump_MAINWEAP_Z = "2";
force force AVS_Jump_PIST_X = "6";
force force AVS_Jump_PIST_Z = "2.5";
force force AVS_Jump_UNARMED_X = "8";
force force AVS_Jump_UNARMED_Z = "5";
force force AVS_Jumping = true;
force force AVS_Rolling = true;
force force AVS_Sliding = true;

// Bundeswehr
force force BWA3_Leopard_ClocknumbersDir_Commander = false;
force force BWA3_NaviPad_showMembers = true;
force force BWA3_Puma_ClocknumbersDir_Commander = false;
force force BWA3_Puma_ClocknumbersDir_Gunner = false;

// Community Base Addons
cba_diagnostic_ConsoleIndentType = -1;
force force cba_diagnostic_watchInfoRefreshRate = 0.2;
force force cba_disposable_dropUsedLauncher = 2;
force force cba_disposable_replaceDisposableLauncher = true;
cba_events_repetitionMode = 1;
force force cba_network_loadoutValidation = 2;
cba_optics_usePipOptics = true;
force force cba_quicktime_qteShorten = false;
cba_ui_notifyLifetime = 4;
cba_ui_StorePasswords = 1;

// cTab
force force ctab_compass_enable = true;
force force ctab_core_bft_mode = 1;
force force ctab_core_defMapStyle = "SAT";
force force ctab_core_gridPrecision = 0;
force force ctab_core_helmetcam_mode = 1;
force force ctab_core_sync_time = 60;
force force ctab_core_uav_mode = 1;
force force ctab_core_useAceMicroDagr = true;
force force ctab_core_useArmaMarker = false;
ctab_core_useMils = false;

// CUP
force force CUP_CheckCfgPatches = false;
force force CUP_Vehicles_PreventBarrelClip = true;

// CUP Static Weapons
force force CUP_staticWeapons_allowMovement = false;
force force CUP_staticWeapons_allowRotation = false;

// DUI - Squad Radar - Indikatoren
force force diwako_dui_indicators_crew_range_enabled = true;
force force diwako_dui_indicators_fov_scale = false;
force force diwako_dui_indicators_icon_buddy = true;
force force diwako_dui_indicators_icon_leader = true;
force force diwako_dui_indicators_icon_medic = true;
force force diwako_dui_indicators_range = 20;
force force diwako_dui_indicators_range_crew = 300;
force force diwako_dui_indicators_range_scale = false;
force force diwako_dui_indicators_rangeLimit = 100;
force force diwako_dui_indicators_show = true;
force force diwako_dui_indicators_size = 1;
force force diwako_dui_indicators_style = "standard";
force force diwako_dui_indicators_useACENametagsRange = true;

// DUI - Squad Radar - Linienkompass
force force diwako_dui_linecompass_ACEFingeringColor = [1,0.66,0,1];
force force diwako_dui_linecompass_AllowNumericDrawBearing = true;
force force diwako_dui_linecompass_CompassAvailableShown = false;
force force diwako_dui_linecompass_compassRange = 70.8442;
force force diwako_dui_linecompass_compassRangeLimit = 50;
force force diwako_dui_linecompass_CustomWaypointColor = [0,0,0.87,1];
force force diwako_dui_linecompass_DefaultIconColor = [0.5,0.87,0.5,1];
force force diwako_dui_linecompass_DrawBearing = 2;
force force diwako_dui_linecompass_Enabled = false;
force force diwako_dui_linecompass_enableOcclusion = false;
force force diwako_dui_linecompass_IconOutline = 0;
force force diwako_dui_linecompass_occlusionFadeSpeed = 3.5;
force force diwako_dui_linecompass_showSpeaking = true;
force force diwako_dui_linecompass_SwapOrder = false;
force force diwako_dui_linecompass_WaypointColor = [0,0,0.87,1];

// DUI - Squad Radar - Main
force force diwako_dui_ace_hide_interaction = true;
force force diwako_dui_colors = "ace";
force force diwako_dui_font = "RobotoCondensed";
force force diwako_dui_icon_style = "nato";
force force diwako_dui_main_hide_dialog = true;
force force diwako_dui_main_hide_ui_by_default = false;
force force diwako_dui_main_squadBlue = [0,0,1,1];
force force diwako_dui_main_squadGreen = [0,1,0,1];
force force diwako_dui_main_squadMain = [1,1,1,1];
force force diwako_dui_main_squadRed = [1,0,0,1];
force force diwako_dui_main_squadYellow = [1,1,0,1];
force force diwako_dui_main_trackingColor = [0.93,0.26,0.93,1];
force force diwako_dui_reset_ui_pos = false;

// DUI - Squad Radar - Namensschilder
force force diwako_dui_nametags_customRankStyle = "[[""PRIVATE"",""CORPORAL"",""SERGEANT"",""LIEUTENANT"",""CAPTAIN"",""MAJOR"",""COLONEL""],[""Pvt."",""Cpl."",""Sgt."",""Lt."",""Capt."",""Maj."",""Col.""]]";
diwako_dui_nametags_deadColor = [0.2,0.2,0.2,1];
force force diwako_dui_nametags_deadRenderDistance = 3.5;
force force diwako_dui_nametags_drawRank = true;
force force diwako_dui_nametags_enabled = false;
force force diwako_dui_nametags_enableFOVBoost = true;
force force diwako_dui_nametags_enableOcclusion = true;
force force diwako_dui_nametags_fadeInTime = 0.05;
force force diwako_dui_nametags_fadeOutTime = 0.5;
force force diwako_dui_nametags_fontGroup = "EtelkaMonospacePro";
force force diwako_dui_nametags_fontGroupNameSize = 8;
force force diwako_dui_nametags_fontName = "RobotoCondensedBold";
force force diwako_dui_nametags_fontNameSize = 10;
diwako_dui_nametags_groupColor = [1,1,1,1];
force force diwako_dui_nametags_groupFontShadow = 1;
diwako_dui_nametags_groupNameOtherGroupColor = [0.6,0.85,0.6,1];
force force diwako_dui_nametags_nameFontShadow = 1;
diwako_dui_nametags_nameOtherGroupColor = [0.2,1,0,1];
force force diwako_dui_nametags_rankNameStyle = "default";
force force diwako_dui_nametags_renderDistance = 10;
force force diwako_dui_nametags_showUnconAsDead = true;
force force diwako_dui_nametags_useLIS = true;
force force diwako_dui_nametags_useSideIsFriendly = true;

// DUI - Squad Radar - Radar
force force diwako_dui_compass_hide_alone_group = true;
force force diwako_dui_compass_hide_blip_alone_group = true;
force force diwako_dui_compass_icon_scale = 1;
force force diwako_dui_compass_opacity = 1;
force force diwako_dui_compass_style = ["\z\diwako_dui\addons\radar\UI\compass_styles\classic\limited.paa","\z\diwako_dui\addons\radar\UI\compass_styles\classic\full.paa"];
force force diwako_dui_compassRange = 35;
force force diwako_dui_compassRefreshrate = 0;
force force diwako_dui_dir_showMildot = false;
force force diwako_dui_dir_size = 1.25;
force force diwako_dui_distanceWarning = 3;
force force diwako_dui_enable_compass = true;
force force diwako_dui_enable_compass_dir = 2;
force force diwako_dui_enable_occlusion = false;
force force diwako_dui_enable_occlusion_cone = 360;
force force diwako_dui_hudScaling = 1;
force force diwako_dui_namelist = true;
force force diwako_dui_namelist_bg = 0;
force force diwako_dui_namelist_only_buddy_icon = false;
force force diwako_dui_namelist_size = 1;
force force diwako_dui_namelist_text_shadow = 2;
force force diwako_dui_namelist_width = 215;
force force diwako_dui_radar_ace_finger = true;
force force diwako_dui_radar_ace_medic = true;
force force diwako_dui_radar_always_show_unit_numbers = false;
force force diwako_dui_radar_compassRangeCrew = 500;
force force diwako_dui_radar_compassRangeLimit = 50;
force force diwako_dui_radar_dir_padding = 25;
force force diwako_dui_radar_dir_shadow = 2;
force force diwako_dui_radar_enable_seat_icons = 2;
force force diwako_dui_radar_group_by_vehicle = false;
force force diwako_dui_radar_icon_opacity = 1;
force force diwako_dui_radar_icon_opacity_no_player = true;
force force diwako_dui_radar_icon_priority_setting = 1;
force force diwako_dui_radar_icon_scale_crew = 6;
force force diwako_dui_radar_leadingZeroes = true;
force force diwako_dui_radar_namelist_hideWhenLeader = false;
force force diwako_dui_radar_namelist_vertical_spacing = 0.75;
force force diwako_dui_radar_occlusion_fade_in_time = 1;
force force diwako_dui_radar_occlusion_fade_time = 10;
force force diwako_dui_radar_pointer_color = [1,0.5,0,1];
force force diwako_dui_radar_pointer_style = "standard";
force force diwako_dui_radar_show_cardinal_points = true;
force force diwako_dui_radar_showSpeaking = true;
force force diwako_dui_radar_showSpeaking_radioOnly = false;
force force diwako_dui_radar_showSpeaking_replaceIcon = true;
force force diwako_dui_radar_sortType = "fireteam2";
force force diwako_dui_radar_sqlFirst = true;
force force diwako_dui_radar_syncGroup = false;
force force diwako_dui_radar_vehicleCompassEnabled = true;
force force diwako_dui_use_layout_editor = false;

// GRAD Civilians
grad_civs_activities_panicCooldown = "[15, 120, 240]";
force grad_civs_cars_animalTransportChance = 0.4;
force grad_civs_cars_animalTransportVehicles = "";
force grad_civs_cars_automaticVehicleGroupSize = true;
grad_civs_cars_globalSpeedLimit = 50;
grad_civs_cars_townSpeedLimit = 30;
force grad_civs_cars_vehicles = "[""C_Van_01_fuel_F"",""C_Hatchback_01_F"",""C_Truck_02_fuel_F"",""C_Truck_02_covered_F"",""C_Offroad_01_F"",""C_SUV_01_F"",""C_Van_01_transport_F"",""C_Van_01_box_F""]";
grad_civs_diagnostics_showFps = false;
grad_civs_diagnostics_showInfoLine = false;
grad_civs_diagnostics_showMisc = false;
grad_civs_diagnostics_showOnMap = false;
grad_civs_diagnostics_showPinkArrows = false;
grad_civs_diagnostics_showSpawnAttempts = false;
grad_civs_diagnostics_showSpeedLimitsOnMap = false;
force grad_civs_gta_enabled = true;
force grad_civs_lifecycle_civClasses = "C_Man_1";
force grad_civs_lifecycle_cleanupCorpses = true;
force grad_civs_lifecycle_minCivOwnerFps = 30;
grad_civs_lifecycle_minCivUpdateTime = 3;
force grad_civs_lifecycle_minServerFps = 40;
force grad_civs_lifecycle_smMultiplicator = 1;
force grad_civs_lifecycle_spawnCandidateHeightLimit = 200;
force grad_civs_lifecycle_spawnCandidateLimitEnabled = true;
force grad_civs_lifecycle_spawnCandidateSpeedLimit = 100;
force grad_civs_lifecycle_spawnOnlyWithPlayers = true;
force grad_civs_lifecycle_spawnRate = 0.5;
force grad_civs_loadout_backpackProbability = 0.5;
force grad_civs_loadout_backpacks = "[]";
force grad_civs_loadout_clothes = "[]";
force grad_civs_loadout_faces = "[]";
force grad_civs_loadout_goggles = "[]";
force grad_civs_loadout_headgear = "[]";
force grad_civs_main_enabled = false;
force grad_civs_mimikry_enabled = true;
force grad_civs_patrol_initialGroupSize = 3;
force grad_civs_patrol_maxCivsOnFoot = 30;
grad_civs_patrol_spawnDistancesOnFoot = "[1000, 4500]";
grad_civs_residents_chatTime = 20;
force grad_civs_residents_maxCivsResidents = 20;
grad_civs_residents_meetNeighborCooldown = 150;
grad_civs_residents_spawnDistancesResidents = "[500,  1000]";
force grad_civs_transit_maxVehiclesInTransit = 5;
force grad_civs_transit_vehicles = "[]";
force grad_civs_voyage_maxCivsInVehicles = 10;
grad_civs_voyage_maxTravelRadius = 0;
grad_civs_voyage_spawnDistancesInVehicles = "[1500, 6000]";

// GRAD slingHelmet
force force GRAD_slingHelmet_additionalList = "";
force force GRAD_slingHelmet_allowAll = true;

// GRAD Trenches
force force grad_trenches_functions_allowBigEnvelope = true;
force force grad_trenches_functions_allowCamouflage = true;
force force grad_trenches_functions_allowDigging = true;
force force grad_trenches_functions_allowEffects = true;
force force grad_trenches_functions_allowGiantEnvelope = true;
force force grad_trenches_functions_allowHitDecay = true;
force force grad_trenches_functions_allowLongEnvelope = true;
force force grad_trenches_functions_allowShortEnvelope = true;
force force grad_trenches_functions_allowSmallEnvelope = true;
force force grad_trenches_functions_allowTextureLock = true;
force force grad_trenches_functions_allowTrenchDecay = true;
force force grad_trenches_functions_allowVehicleEnvelope = true;
force force grad_trenches_functions_bigEnvelopeDamageMultiplier = 2;
force force grad_trenches_functions_bigEnvelopeDigTime = 40;
force force grad_trenches_functions_bigEnvelopeRemovalTime = -1;
force force grad_trenches_functions_buildFatigueFactor = 1;
force force grad_trenches_functions_camouflageRequireEntrenchmentTool = true;
force force grad_trenches_functions_createTrenchMarker = false;
force force grad_trenches_functions_decayTime = 1800;
force force grad_trenches_functions_giantEnvelopeDamageMultiplier = 1;
force force grad_trenches_functions_giantEnvelopeDigTime = 90;
force force grad_trenches_functions_giantEnvelopeRemovalTime = -1;
force force grad_trenches_functions_hitDecayMultiplier = 1;
force force grad_trenches_functions_LongEnvelopeDigTime = 100;
force force grad_trenches_functions_LongEnvelopeRemovalTime = -1;
force force grad_trenches_functions_playersInAreaRadius = 0;
force force grad_trenches_functions_shortEnvelopeDamageMultiplier = 2;
force force grad_trenches_functions_shortEnvelopeDigTime = 15;
force force grad_trenches_functions_shortEnvelopeRemovalTime = -1;
force force grad_trenches_functions_smallEnvelopeDamageMultiplier = 3;
force force grad_trenches_functions_smallEnvelopeDigTime = 30;
force force grad_trenches_functions_smallEnvelopeRemovalTime = -1;
force force grad_trenches_functions_stopBuildingAtFatigueMax = true;
force force grad_trenches_functions_textureLockDistance = 5;
force force grad_trenches_functions_timeoutToDecay = 3600;
force force grad_trenches_functions_vehicleEnvelopeDamageMultiplier = 1;
force force grad_trenches_functions_vehicleEnvelopeDigTime = 120;
force force grad_trenches_functions_vehicleEnvelopeRemovalTime = -1;
force force grad_trenches_functions_vehicleTrenchBuildSpeed = 5;

// LAMBS Danger
force force lambs_danger_cqbRange = 60;
force force lambs_danger_disableAIAutonomousManoeuvres = false;
force force lambs_danger_disableAIDeployStaticWeapons = false;
force force lambs_danger_disableAIFindStaticWeapons = false;
force force lambs_danger_disableAIHideFromTanksAndAircraft = false;
force force lambs_danger_disableAIPlayerGroup = false;
force force lambs_danger_disableAIPlayerGroupReaction = false;
force force lambs_danger_disableAutonomousFlares = false;
force force lambs_danger_disableAutonomousSmokeGrenades = false;
force force lambs_danger_panicChance = 0.1;

// LAMBS Danger Eventhandlers
force force lambs_eventhandlers_ExplosionEventHandlerEnabled = true;
force force lambs_eventhandlers_ExplosionReactionTime = 9;

// LAMBS Danger WP
force force lambs_wp_autoAddArtillery = false;

// LAMBS Main
force force lambs_main_combatShareRange = 200;
force force lambs_main_debug_drawAllUnitsInVehicles = false;
force force lambs_main_debug_Drawing = false;
force force lambs_main_debug_FSM = false;
force force lambs_main_debug_FSM_civ = false;
force force lambs_main_debug_functions = false;
force force lambs_main_debug_RenderExpectedDestination = false;
force force lambs_main_disableAICallouts = false;
force force lambs_main_disableAIDodge = false;
force force lambs_main_disableAIFleeing = false;
force force lambs_main_disableAIGestures = false;
force force lambs_main_disableAutonomousMunitionSwitching = false;
force force lambs_main_disablePlayerGroupSuppression = false;
force force lambs_main_indoorMove = 0.1;
force force lambs_main_maxRevealValue = 1;
force force lambs_main_minFriendlySuppressionDistance = 5;
force force lambs_main_minObstacleProximity = 5;
force force lambs_main_minSuppressionRange = 50;
force force lambs_main_radioBackpack = 2000;
force force lambs_main_radioDisabled = false;
force force lambs_main_radioEast = 500;
force force lambs_main_radioGuer = 500;
force force lambs_main_radioShout = 100;
force force lambs_main_radioWest = 500;

// LAxemann's Suppress
force force L_Suppress_buildup = 0.5;
force force L_Suppress_enabled = true;
force force L_Suppress_flyByEffects = true;
force force L_Suppress_flyByIntensity = 0.8;
force force L_Suppress_halting = true;
force force L_Suppress_intensity = 0.8;
force force L_Suppress_playerSwabEnabled = true;
force force L_Suppress_recovery = 1;

// Metis Enhanced
force force mts_armory_allowPlayerDBConnection = false;
force force mts_armory_openUIActionMenu = "ace_interaction";
force force mts_cords_enabled = true;
force force mts_cords_playerIDs = "[""""]";
force force mts_cutter_bushcutter_duration = 10;
force force mts_cutter_bushcutter_enabled = true;
force force mts_cutter_bushcutter_requireItem = false;
force force mts_cutter_grasscutter_duration = 5;
force force mts_cutter_grasscutter_enabled = true;
force force mts_cutter_grasscutter_size = 1;
force force mts_drill_UIEnabled = true;
force force mts_zeus_3DENCommentsColor = [0,1,0.75,1];
force force mts_zeus_ACEUnconsciousIconColor = [0.9,0,0,1];
force force mts_zeus_enable3DENComments = true;
force force mts_zeus_enableACEUnconsciousIcon = true;

// Simplex Support Services
force force SSS_setting_adminFullAccess = true;
force force SSS_setting_adminLimitSide = false;
force force SSS_setting_cleanupCrew = true;
force force SSS_setting_deleteVehicleOnEntityRemoval = false;
force force SSS_setting_directActionRequirement = false;
force force SSS_setting_GiveUAVTerminal = true;
force force SSS_setting_milsimModeArtillery = false;
force force SSS_setting_milsimModeCAS = false;
force force SSS_setting_milsimModeLogistics = false;
force force SSS_setting_milsimModeTransport = false;
force force SSS_setting_removeSupportOnVehicleDeletion = true;
force force SSS_setting_resetVehicleOnRTB = true;
force force SSS_setting_restoreCrewOnRTB = true;
force force SSS_setting_slingLoadSearchRadius = 100;
force force SSS_setting_slingLoadWhitelist = "";
force force SSS_setting_useChatNotifications = false;

// Zeus Enhanced
force force zen_area_markers_editableMarkers = 0;
force force zen_building_markers_enabled = true;
force force zen_camera_adaptiveSpeed = true;
force force zen_camera_defaultSpeedCoef = 1;
force force zen_camera_fastSpeedCoef = 1;
force force zen_camera_followTerrain = false;
force force zen_common_ascensionMessages = false;
force force zen_common_autoAddObjects = true;
force force zen_common_cameraBird = false;
force force zen_common_darkMode = true;
force force zen_common_disableGearAnim = true;
force force zen_common_preferredArsenal = 1;
force force zen_compat_ace_hideModules = false;
force force zen_context_menu_enabled = 2;
force force zen_context_menu_overrideWaypoints = false;
force force zen_editor_addGroupIcons = true;
force force zen_editor_addModIcons = false;
force force zen_editor_declutterEmptyTree = false;
force force zen_editor_disableLiveSearch = false;
force force zen_editor_moveDisplayToEdge = true;
force force zen_editor_parachuteSounds = true;
force force zen_editor_previews_enabled = true;
force force zen_editor_randomizeCopyPaste = false;
force force zen_editor_removeWatermark = true;
force force zen_editor_unitRadioMessages = 0;
force force zen_placement_enabled = true;
force force zen_remote_control_cameraExitPosition = 2;
force force zen_visibility_enabled = 1;
force force zen_visibility_maxDistance = 1500;
force force zen_vision_enableBlackHot = false;
force force zen_vision_enableBlackHotGreenCold = false;
force force zen_vision_enableBlackHotRedCold = false;
force force zen_vision_enableGreenHotCold = false;
force force zen_vision_enableNVG = true;
force force zen_vision_enableRedGreenThermal = false;
force force zen_vision_enableRedHotCold = false;
force force zen_vision_enableWhiteHot = true;
force force zen_vision_enableWhiteHotRedCold = false;

// Zeus Enhanced - Attribute
force force zen_attributes_enableAbilities = true;
force force zen_attributes_enableAmmo = true;
force force zen_attributes_enableAmmoCargo = true;
force force zen_attributes_enableArsenal = true;
force force zen_attributes_enableBuildingMarker = true;
force force zen_attributes_enableDamage = true;
force force zen_attributes_enableEngine = true;
force force zen_attributes_enableExecute = true;
force force zen_attributes_enableFuel = true;
force force zen_attributes_enableFuelCargo = true;
force force zen_attributes_enableGarage = true;
force force zen_attributes_enableGroupBehaviour = true;
force force zen_attributes_enableGroupCombatMode = true;
force force zen_attributes_enableGroupExecute = true;
force force zen_attributes_enableGroupFormation = true;
force force zen_attributes_enableGroupID = true;
force force zen_attributes_enableGroupSide = true;
force force zen_attributes_enableGroupSkill = true;
force force zen_attributes_enableGroupSpeed = true;
force force zen_attributes_enableGroupStance = true;
force force zen_attributes_enableHealth = true;
force force zen_attributes_enableInventory = true;
force force zen_attributes_enableLights = true;
force force zen_attributes_enableMarkerAlpha = true;
force force zen_attributes_enableMarkerColor = true;
force force zen_attributes_enableMarkerText = true;
force force zen_attributes_enableName = true;
force force zen_attributes_enablePlateNumber = true;
force force zen_attributes_enableRank = true;
force force zen_attributes_enableRepairCargo = true;
force force zen_attributes_enableRespawnPosition = true;
force force zen_attributes_enableRespawnVehicle = true;
force force zen_attributes_enableSensors = true;
force force zen_attributes_enableSkill = true;
force force zen_attributes_enableSkills = true;
force force zen_attributes_enableStance = true;
force force zen_attributes_enableStates = true;
force force zen_attributes_enableTraits = true;
force force zen_attributes_enableVehicleLock = true;
force force zen_attributes_enableWaypointBehaviour = true;
force force zen_attributes_enableWaypointCombatMode = true;
force force zen_attributes_enableWaypointFormation = true;
force force zen_attributes_enableWaypointLoiterAltitude = true;
force force zen_attributes_enableWaypointLoiterDirection = true;
force force zen_attributes_enableWaypointLoiterRadius = true;
force force zen_attributes_enableWaypointSpeed = true;
force force zen_attributes_enableWaypointTimeout = true;
force force zen_attributes_enableWaypointType = true;

// Zeus Enhanced - Fraktionsfilter
force force zen_faction_filter_0_ASA_OPFOR_WINTER_OPFOR_Winter3 = true;
force force zen_faction_filter_0_ASA_OPFOR_WINTER_OPFOR_Winter3_groups = true;
force force zen_faction_filter_0_CUP_O_ChDKZ = true;
force force zen_faction_filter_0_CUP_O_RU = true;
force force zen_faction_filter_0_CUP_O_RUS_M = true;
force force zen_faction_filter_0_CUP_O_SLA = true;
force force zen_faction_filter_0_CUP_O_TK = true;
force force zen_faction_filter_0_CUP_O_TK_MILITIA = true;
force force zen_faction_filter_0_CUP_Static_Ships = true;
force force zen_faction_filter_0_OPF_F = true;
force force zen_faction_filter_0_OPF_G_F = true;
force force zen_faction_filter_0_OPF_GEN_F = true;
force force zen_faction_filter_0_OPF_R_F = true;
force force zen_faction_filter_0_OPF_T_F = true;
force force zen_faction_filter_0_Redd_Vehicles = true;
force force zen_faction_filter_1_asa_bw = true;
force force zen_faction_filter_1_ASA_CIA_CIA_Black_Ops = true;
force force zen_faction_filter_1_ASA_EAF_Estonian_Armed_Forces = true;
force force zen_faction_filter_1_ASA_Japanese_Defense_Forces = true;
force force zen_faction_filter_1_ASA_LaAF_Latvian_Armed_Forces = true;
force force zen_faction_filter_1_ASA_LiAF_Lithuanian_Armed_Forces = true;
force force zen_faction_filter_1_ASA_POLICEW_Western_Police = true;
force force zen_faction_filter_1_asa_unitsFleck = true;
force force zen_faction_filter_1_asa_unitsTropen = true;
force force zen_faction_filter_1_asa_unitsWinter = true;
force force zen_faction_filter_1_BLU_CTRG_F = true;
force force zen_faction_filter_1_BLU_F = true;
force force zen_faction_filter_1_BLU_G_F = true;
force force zen_faction_filter_1_BLU_GEN_F = true;
force force zen_faction_filter_1_BLU_T_F = true;
force force zen_faction_filter_1_BLU_W_F = true;
force force zen_faction_filter_1_BWA3_Faction_Fleck = true;
force force zen_faction_filter_1_BWA3_Faction_Multi = true;
force force zen_faction_filter_1_BWA3_Faction_Tropen = true;
force force zen_faction_filter_1_BWAdapt_ = true;
force force zen_faction_filter_1_CUP_B_AFU = true;
force force zen_faction_filter_1_CUP_B_CDF = true;
force force zen_faction_filter_1_CUP_B_CZ = true;
force force zen_faction_filter_1_CUP_B_GB = true;
force force zen_faction_filter_1_CUP_B_GER = true;
force force zen_faction_filter_1_CUP_B_HIL = true;
force force zen_faction_filter_1_CUP_B_RNZN = true;
force force zen_faction_filter_1_CUP_B_US_Army = true;
force force zen_faction_filter_1_CUP_B_USMC = true;
force force zen_faction_filter_1_CUP_Static_Ships = true;
force force zen_faction_filter_1_Redd_Vehicles = true;
force force zen_faction_filter_2_ASA_Eastern_Helicopters = true;
force force zen_faction_filter_2_CUP_I_NAPA = true;
force force zen_faction_filter_2_CUP_I_PMC_ION = true;
force force zen_faction_filter_2_CUP_I_RACS = true;
force force zen_faction_filter_2_CUP_I_TK_GUE = true;
force force zen_faction_filter_2_CUP_I_UN = true;
force force zen_faction_filter_2_CUP_Static_Ships = true;
force force zen_faction_filter_2_IND_C_F = true;
force force zen_faction_filter_2_IND_E_F = true;
force force zen_faction_filter_2_IND_F = true;
force force zen_faction_filter_2_IND_G_F = true;
force force zen_faction_filter_2_IND_L_F = true;
force force zen_faction_filter_3_CIV_F = true;
force force zen_faction_filter_3_CIV_IDAP_F = true;
force force zen_faction_filter_3_CUP_C_CHERNARUS = true;
force force zen_faction_filter_3_CUP_C_RU = true;
force force zen_faction_filter_3_CUP_C_SAHRANI = true;
force force zen_faction_filter_3_CUP_C_TK = true;
force force zen_faction_filter_3_IND_L_F = true;
